version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://${{ secrets.CONTAINER_NAME }}/~/hhive
      SPRING_DATASOURCE_USERNAME: ${{ secrets.PROD_DB_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
