version: "3"
services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: hhiveServer
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.PROD_DB_NAME }}
    ports:
      - "3306:3306"
    volumes:
      - ../${{ secrets.PROD_DB_NAME }}-mysql:/var/lib/mysql
      - ../${{ secrets.PROD_DB_NAME }}-mysql-conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

  spring:
    container_name: hhive-spring
    image: eunchaev1006/hhive
    expose:
      - 8080
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: hhive-redis-server
    ports:
      - "6379:6379"
    restart: always




